module.exports = function (sequelize, DataTypes) {
  return sequelize.define('ImageTab', {
    StudyKey: {
      type: DataTypes.INTEGER,
      primaryKey: true,
      allowNull: false
    },
    SeriesKey: {
      type: DataTypes.INTEGER,
      primaryKey: true,
      allowNull: false
    },
    ImageKey: {
      type: DataTypes.INTEGER,
      primaryKey: true,
      allowNull: false
    },
    StudyInsUID: {
      type: DataTypes.STRING(64),
      allowNull: false
    },
    SeriesInsUID: {
      type: DataTypes.STRING(64),
      allowNull: false
    },
    SOPInstanceUID: {
      type: DataTypes.STRING(64),
      allowNull: false
    },
    SOPClassUID: DataTypes.STRING(64),
    Path: DataTypes.STRING(255),
    FName: DataTypes.STRING(255),
    InstanceNum: DataTypes.STRING(12),
    CurSeqNum: DataTypes.INTEGER,
    Window: DataTypes.INTEGER,
    Lev: DataTypes.INTEGER,
    ContentDate: DataTypes.STRING(8),
    ContentTime: DataTypes.STRING(16),
    AcqDate: DataTypes.STRING(8),
    AcqTime: DataTypes.STRING(16),
    ViewPosition: DataTypes.STRING(255),
    Laterality: DataTypes.STRING(64),
    ImageComments: DataTypes.STRING(255),
    AdditionalDesc: DataTypes.STRING(32),
    ImageOrientation: DataTypes.STRING(64),
    ImagePosition: DataTypes.STRING(64),
    PixelSpacing: DataTypes.STRING(20),
    PixelRows: DataTypes.INTEGER,
    PixelColumns: DataTypes.INTEGER,
    BitsAllocated: DataTypes.INTEGER,
    GeomStatus: DataTypes.INTEGER,
    ArchStatus: DataTypes.INTEGER,
    ArchPath: DataTypes.STRING(128),
    DelFlag: DataTypes.INTEGER,
    VerifyFlag: DataTypes.INTEGER,
    HideFlag: DataTypes.INTEGER,
    KeyFlag: DataTypes.INTEGER,
    CompStatus: DataTypes.INTEGER,
    PresentationStateData: DataTypes.STRING(255),
    SharpenValue: DataTypes.INTEGER,
    LUTData: DataTypes.STRING(255),
    ImageSize: DataTypes.INTEGER,
    CompSize: DataTypes.INTEGER,
    LTStorageID: DataTypes.INTEGER,
    STStorageID: DataTypes.INTEGER,
    WebStorageID: DataTypes.INTEGER,
    InsertDate: DataTypes.STRING(8),
    InsertTime: DataTypes.STRING(8),
    HospitalID: DataTypes.INTEGER,
    Reserved1: DataTypes.INTEGER,
    Reserved2: DataTypes.INTEGER,
    Reserved3: DataTypes.INTEGER,
    Reserved4: DataTypes.STRING(255),
    Reserved5: DataTypes.STRING(255),
    Reserved6: DataTypes.STRING(255),
    Reserved7: DataTypes.STRING(255),
    Reserved8: DataTypes.STRING(255),
    Reserved9: DataTypes.STRING(255),
    Reserved10: DataTypes.STRING(255),
    ImageType: DataTypes.STRING(64),
    FMXData: DataTypes.STRING(255),
    ImageUID: DataTypes.STRING(64),
    ImageNum: DataTypes.STRING(12),
    VDirPath: DataTypes.STRING(255),
    PPASTATUS: DataTypes.INTEGER,
    MovPath: DataTypes.STRING(255),
    MovFname: DataTypes.STRING(255),
    MovieFlag: DataTypes.INTEGER,
    CodecType: DataTypes.STRING(128),
    FrameRate: DataTypes.FLOAT,
    FrameTime: DataTypes.FLOAT,
    RecStartDate: DataTypes.STRING(8),
    RecStartTime: DataTypes.STRING(6),
    RecEndDate: DataTypes.STRING(8),
    RecEndTime: DataTypes.STRING(6),
    MovSTStorageID: DataTypes.INTEGER,
    test: DataTypes.STRING(244),
    FrameCnt: DataTypes.INTEGER,
    SamplePerPixel: DataTypes.INTEGER,
    BitsStored: DataTypes.INTEGER,
    Photometric: DataTypes.INTEGER,
    PixelRepresentation: DataTypes.INTEGER,
    CompressionType: DataTypes.INTEGER,
    IsGray: DataTypes.INTEGER,
    HighBit: DataTypes.INTEGER,
    BitsPerPixel: DataTypes.INTEGER,
    KeyImage_UserID: DataTypes.STRING(32),
    REPRESENTATIONFLAG: DataTypes.INTEGER,
    MobileStorageID: DataTypes.INTEGER,
    MobileStoredTime: DataTypes.STRING(32),
    DAP: DataTypes.DECIMAL(10, 6),
    AcqDeviceProDesc: DataTypes.STRING(64),
    RegionSpatialFormat: DataTypes.INTEGER,
    FilterMaterial: DataTypes.STRING(16),
    PixelAspectRatio: DataTypes.INTEGER,
    RecDisplayFrameRate: DataTypes.INTEGER,
    SpacingBtwSlice: DataTypes.DECIMAL(16, 6),
    RescaleIntercept: DataTypes.DECIMAL(16, 6),
    RescaleSlope: DataTypes.DECIMAL(16, 6)
  },
  {
    indexes: [
      { fields: ['StudyKey', 'SeriesKey'] },
      { fields: ['SOPInstanceUID'] }
    ],
    tableName: 'ImageTab'
  });
};
